### ISSUE TITLE
[feat] ER図の作成

### ISSUE THREAD

**Issue by Sora339** [balckowl/ai-manga#4]

**Comment by Sora339** [comment]
![image](https://github.com/user-attachments/assets/ed7f84e4-86c8-4b59-86b5-78da6ec32bb1)

**Comment by Sora339** [comment]
Comicのスキーマ変更
![hackU](https://github.com/user-attachments/assets/5bfbfa81-171c-498a-9c9f-386047b8670f)

**Comment by balckowl** [comment]
LGTM
